import * as vscode from 'vscode';
import { JiraIssueData } from './adapters/JiraTrackerAdapter';
import { sendLlmRequest, LlmMessage } from './llmService';

/**
 * Planner 모듈.
 *
 * Jira 이슈 데이터를 LLM에 전달하여
 * "수정 파일 목록, 실행 명령어, 작업 순서"가 담긴
 * Markdown 형식의 작업 계획서를 생성한다.
 */

// ─── 시스템 프롬프트 ───

const SYSTEM_PROMPT = `You are a senior software engineer acting as a **Work Planner**.
Your task is to analyze a Jira issue and generate a step-by-step work plan in Markdown format.

## Output Requirements
1. **Language**: Write entirely in Korean (한국어).
2. **Format**: Use Markdown with the following sections:
   - ## 📋 작업 요약 — 1-2줄 요약
   - ## 📂 수정 대상 파일 — 수정/생성/삭제할 파일 목록 (예상)
   - ## 🔧 실행 명령어 — 필요한 CLI 명령어 (빌드, 테스트, 마이그레이션 등)
   - ## 📝 작업 순서 — 체크리스트 형식의 단계별 작업 계획
   - ## ⚠️ 주의사항 — 사이드이펙트, 의존성 충돌 등 주의점
3. **Checklist**: Use \`- [ ]\` 형식의 체크리스트 (실행 가능한 단위로 분할).
4. **Detail**: Each checklist item should be specific enough for a developer to execute immediately.
5. **Context-Aware**: If an Epic is provided, consider the broader project context.

## Rules
- Do NOT include code implementation. Focus on the PLAN only.
- Do NOT make assumptions about the tech stack unless mentioned in the issue.
- If the issue is vague, list questions the developer should clarify before starting.`;

// ─── 이슈 → 프롬프트 변환 ───

/**
 * JiraIssueData를 LLM에 보낼 사용자 메시지로 변환한다.
 */
function buildUserPrompt(issue: JiraIssueData): string {
    const parts: string[] = [];

    parts.push(`# Jira Issue: ${issue.key}`);
    parts.push(`**제목**: ${issue.summary}`);
    parts.push(`**유형**: ${issue.issueType} | **우선순위**: ${issue.priority} | **상태**: ${issue.status}`);

    if (issue.assignee) {
        parts.push(`**담당자**: ${issue.assignee}`);
    }

    if (issue.labels.length > 0) {
        parts.push(`**라벨**: ${issue.labels.join(', ')}`);
    }

    parts.push('');

    // 에픽 컨텍스트
    if (issue.epic) {
        parts.push(`## 상위 에픽: ${issue.epic.key} — ${issue.epic.summary}`);
        if (issue.epic.description) {
            parts.push(issue.epic.description);
        }
        parts.push('');
    }

    // 본문
    parts.push('## 이슈 설명');
    parts.push(issue.description ?? '(설명 없음)');
    parts.push('');

    // 코멘트
    if (issue.comments.length > 0) {
        parts.push(`## 코멘트 (${issue.comments.length}개)`);
        for (const comment of issue.comments) {
            const date = new Date(comment.created).toLocaleString('ko-KR');
            parts.push(`### ${comment.author} (${date})`);
            parts.push(comment.body);
            parts.push('');
        }
    }

    parts.push('---');
    parts.push('위 Jira 이슈를 분석하고, Markdown 형식의 작업 계획서를 생성해 주세요.');

    return parts.join('\n');
}

// ─── 계획서 생성 ───

/**
 * Jira 이슈 데이터를 기반으로 LLM을 호출하여 작업 계획서를 생성한다.
 *
 * @param issue - Jira 이슈 데이터
 * @param apiKey - OpenAI API 키 (빈 문자열이면 Copilot만 사용)
 * @param token - 취소 토큰
 * @returns 생성된 작업 계획서 (Markdown 텍스트)
 */
export async function generateWorkPlan(
    issue: JiraIssueData,
    apiKey: string,
    token: vscode.CancellationToken
): Promise<{ plan: string; model: string; provider: string }> {
    const messages: LlmMessage[] = [
        { role: 'system', content: SYSTEM_PROMPT },
        { role: 'user', content: buildUserPrompt(issue) },
    ];

    const result = await sendLlmRequest(messages, apiKey, token);

    // 계획서 헤더 추가
    const header = [
        `> 🤖 Generated by **${result.model}** (${result.provider})`,
        `> 📌 Issue: **${issue.key}** — ${issue.summary}`,
        '',
        '---',
        '',
    ].join('\n');

    return {
        plan: header + result.text,
        model: result.model,
        provider: result.provider,
    };
}
